### ISSUE TITLE
# To-Do List

### ISSUE THREAD

**Issue by CelestialAbyss** [Project-Vyre/Finality-Core#1]
Since we are beginning to run into limitations with KubeJS, a core mod is now necessary.

### High Priority

- [x] Change ID and display name for the following items...
  - [x] Living Nether Wart - Item ID: `finality:living_nether_wart`
  - [x] Living Nether Wart Spores - Item ID: `finality:living_nether_wart_spores`

### Intermediate Priority

- [ ] Add Creative Tab
- [x] Transfer from KubeJS and implement custom Patchouli guide book and lang gen for easier writing, translation and maintenance. Also because Patchouli guidebooks written using the provided patchouli books folder does not utilize the assets folder unless registered via a mod.

### Low Priority

These are a bit lower in terms of priority due to difficulty.

- [ ] Custom Potato Cannon 
- [ ] Custom Backtank 
- [ ] Transfer armor and item responsibility to give them *actual* power to replace Avaritia.

---

- [x] Reminder to self: Add the `development` label.
